# Generated by Django 5.0.4 on 2024-04-07 08:17

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('newmanager', django.db.models.manager.Manager()),
            ],
        ),
    ]
